name: Build and test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    if: github.repository == 'apache/orc-format'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17

    - uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: bufbuild/buf-lint-action@v1
      with:
        input: "src/main/proto"

    - name: Install
      run: |
        ./mvnw install
