name: Publish Snapshot

on:
  push:
    branches:
    - branch-1.1

jobs:
  publish-snapshot:
    if: github.repository == 'apache/orc-format'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17

    - name: Publish snapshot
      env:
        ASF_USERNAME: ${{ secrets.NEXUS_USER }}
        ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
      run: |
        echo "<settings><servers><server><id>apache.snapshots.https</id><username>$ASF_USERNAME</username><password>$ASF_PASSWORD</password></server></servers></settings>" > settings.xml
        ./mvnw --settings settings.xml -nsu -ntp -DskipTests deploy
